# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
  # trigger only when the csproj file has changed.
    include:
    - "*.csproj"

pool:
  vmImage: ubuntu-latest

variables:
  - name: csproj_packages
    value: ""
  - name: deprecated_packages
    value: Newtonsoft.Json

jobs:
  - job: CheckDeprecatedNugetPackages
    displayName: 'Check for deprecated nuget packages'
    steps:
    - powershell: |
        $local_csproj_packages = Get-Content *.csproj | Find "<PackageReference Include"
        Write-Host "##vso[task.setvariable variable=csproj_packages;]$local_csproj_packages"

    - bash: |
        for package in ${{ variables.deprecated_packages }}; do
          if grep -q $package $csproj_packages; then
            echo "Warning: Deprecated package $package should not be used."
          fi
        done